package grpcmw

import (
	"github.com/google/uuid"
	"strings"
	"testing"

	"golang.org/x/net/context"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"
)

var (
	unaryInfo = &grpc.UnaryServerInfo{
		FullMethod: "TestService.UnaryMethod",
	}
)

func shortStringValidator(requestID string) bool {
	if len(requestID) < 4 {
		return false
	}
	return true
}

func TestUnaryServerWithoutRequestID(t *testing.T) {
	unaryHandler := func(ctx context.Context, req interface{}) (interface{}, error) {
		requestID := FromContext(ctx)
		if requestID == "" {
			t.Errorf("requestID must be generated by interceptor")
		}

		if got, want := FromContext(ctx), requestID; got != want {
			t.Errorf("expect requestID to %q, but got %q", want, got)
		}

		return "output", nil
	}

	ctx := context.Background()
	_, err := UnaryServerInterceptor()(ctx, "xyz", unaryInfo, unaryHandler)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestUnaryServerWithReqeustID(t *testing.T) {
	requestID := uuid.NewString()

	unaryHandler := func(ctx context.Context, req interface{}) (interface{}, error) {
		if got, want := FromContext(ctx), requestID; got != want {
			t.Errorf("expect requestID to %q, but got %q", want, got)
		}

		if got, want := FromContext(ctx), requestID; got != want {
			t.Errorf("expect requestID to %q, but got %q", want, got)
		}
		return "output", nil
	}

	ctx := context.Background()
	md := metadata.Pairs(DefaultXRequestIDKey, requestID)
	ctx = metadata.NewIncomingContext(ctx, md)
	_, err := UnaryServerInterceptor()(ctx, "xyz", unaryInfo, unaryHandler)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestUnaryServerWithReqeustIDChain(t *testing.T) {
	requestID := uuid.NewString()

	unaryHandler := func(ctx context.Context, req interface{}) (interface{}, error) {
		gotRequestID := FromContext(ctx)

		requestIDs := strings.Split(gotRequestID, ",")
		if got, want := len(requestIDs), 2; got != want {
			t.Errorf("expect the number of request id to %d, but got %d", want, got)
		}
		if got, want := requestIDs[0], requestID; got != want {
			t.Errorf("expect first request id to %q, but got %q", want, got)
		}
		return "output", nil
	}

	ctx := context.Background()
	md := metadata.Pairs(DefaultXRequestIDKey, requestID)
	ctx = metadata.NewIncomingContext(ctx, md)
	_, err := UnaryServerInterceptor(ChainRequestID())(ctx, "xyz", unaryInfo, unaryHandler)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestUnaryServerWithValidator(t *testing.T) {
	requestID := "xyz"

	unaryHandler := func(ctx context.Context, req interface{}) (interface{}, error) {
		if got, want := FromContext(ctx), requestID; got == want {
			t.Errorf("original request id should be invalid")
		}
		return "output", nil
	}

	ctx := context.Background()
	md := metadata.Pairs(DefaultXRequestIDKey, requestID)
	ctx = metadata.NewIncomingContext(ctx, md)
	_, err := UnaryServerInterceptor(RequestIDValidator(shortStringValidator))(ctx, "xyz", unaryInfo, unaryHandler)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}
